behaviors:
  MPTagAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 409600
      learning_rate: 0.0003
      beta: 1e-2
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    keep_checkpoints: 5
    max_steps: 150000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: false
    self_play:
      save_steps: 5000
      team_change: 10000
      swap_steps: 2500
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
